server:
  port: 8889
  session:
    timeout: 3600  # session最大超时时间(分钟)，默认为30，这里设置为6小时
    cookie:
      max-age: 216000    # 单位为秒，设置为6小时
  tomcat:
    max-threads: 512
    uri-encoding: utf-8
spring:
  application:
    name: hongqu-supplier-api-prod
  datasource:
    url: jdbc:mysql://rm-xxxx.mysql.rds.aliyuncs.com:3306/hongqu_prod?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: xxxx
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 50
    min-idle: 50
    max-idle: 200
    max-active: 200
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

  mail:
    host: smtp.mxhichina.com
    port: 25
    username: xxx@xxx.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          starttls:
            enable: false
            required: false
  session:
    store-type: redis
    redis:
      namespace: supplier
  redis:
    host: r-xxxx.redis.rds.aliyuncs.com
    database: 0
    port: 6379
    password: xxxx
    pool:
      max-active: 3000
      max-wait: 3000
      max-idle: 200
      min-idle: 50
    timeout: 5000
logging:
  file: ./logs/${spring.application.name}.log

security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: admin
    password: xxxxx

management:
  port: 8889
  address: 127.0.0.1
  context-path: /admin
  security:
    role: SUPERUSER

endpoints:
  shutdown:
    enabled: true
    sensitive: false
    path: /shutdown


aliyun:
  accessKeyId: xxxx
  accessKeySecret: xxxx
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket: hq-prod
    host: https://oss.hq.xxxx.com
